### Get all agents

GET http://localhost:7000/agents

### Get an agent by identifier

GET http://localhost:7000/agents/clothes_provider


### Get all tools

GET http://localhost:7001/tools

### Get a tool by identifier

GET http://localhost:7001/tools/file_reader_api

### Get all tools

GET http://localhost:7122/openapi.json

### Get all tools

GET http://localhost:7121/openapi.json

### Get all swarms

GET http://localhost:7000/swarms

### Get a swarm by identifier

GET http://localhost:7000/swarms/file_swarm


### Agent health check

GET http://localhost:10008/health


### Send single message to an assistant agent (Ej. clothes_provider - port 10001)

POST http://localhost:10007/chat
content-type: application/json

{
    "role": "user",
    "content": "list files",
    "name": "username"
}


### Initiate a new conversation with a user-proxy agent (clothes_user_proxy - port 10002)

POST http://localhost:10006/conversation
content-type: application/json

{
    "swarm": "file_swarm",
    "user": "username",
    "request": "Hola"
}

### Initiate a new conversation with a user-proxy agent (clothes_user_proxy - port 10002)

POST http://localhost:10002/conversation
content-type: application/json

{
    "swarm": "stylist_swarm",
    "user": "username",
    "request": "Como sabe clothes_provider que ropas hay en el armario?"
}

### Check the conversation status

GET http://localhost:10006/conversation/username/username_71f8167f-be27-45b7-ae38-cbc804c47c3d

### Send new reply to a conversation

POST http://localhost:10006/reply
content-type: application/json

{
    "user_id": "username",
    "conversation_id": "username_71f8167f-be27-45b7-ae38-cbc804c47c3d",
    "content": "pa ti mi cola"
}



### Send single message to an assistant agent (Ej. clothes_provider - port 10001)

POST http://localhost:10007/chat
content-type: application/json

{
    "role": "user",
    "content": "listame los archivos",
    "name": "username"
}

### Initiate a new conversation with a user-proxy agent (clothes_user_proxy - port 10002)

POST http://localhost:10006/conversation
content-type: application/json

{
    "swarm": "file_swarm",
    "user": "username",
    "request": "lista"
}
### Check the conversation status

GET http://localhost:10006/conversation/username/username_a8a9c96f-a3ce-4ff7-9e56-baea8bab2dee
